---
title: "A promising strategy for wood turtle conservation.
Using headstarting to boost growth and survival in a threatened population"
subtitle: |
  <span style="color: white; font-size: 1.2em;">Références </span><br>
  <hr style="border: 1px solid white; width: 100%; margin: 0.5em auto;">
  
  <span style="color: white; font-size: 1.2em;">
  <strong>Félicia Beaulieu</strong> | 
    <a href="mailto:felicia.beaulieu@hotmail.com" style="color: white">felicia.beaulieu@hotmail.com</a>
  </span><br>
  <span style="color: white; font-size: 1em;">Université Laval</span>
format:
  html:
    toc: false
    number-sections: false
    self-contained: true 
    title-block-banner: "#596548" # vert foncé
---

### Introduction

1.  Environnement et Changement climatique Canada. 2020. Programme de rétablissement de la tortue des bois (*Glyptemys insculpta*) au Canada, Série de Programmes de rétablissement de la Loi sur les espèces en péril, Ottawa, vi + 55 p. <https://wildlife-species.canada.ca/species-risk-registry/virtual_sara/files/plans/rs_wood_turtle_f_final.pdf>

2.  Équipe de rétablissement des tortues du québec. 2019. Plan de Rétablissement de la tortue des bois (*Glyptemys Insculpta*) au Québec 2020-2030. <https://mffp.gouv.qc.ca/documents/faune/plan_retablissement_tortue-des-bois_2020-2030.pdf>

3.  van Dijk, P.P. & Harding, J. 2011. Glyptemys insculpta (errata version published in 2016). The IUCN Red List of Threatened Species 2011: e.T4965A97416259. https://dx.doi.org/10.2305/IUCN.UK.2011-1.RLTS.T4965A11102820.en. Accessed on 27 August 2025.

### Methods

4.  Parcs Canada. 2023. Protéger la tortue des bois en péril – Parc national de la Mauricie. Consulté sur <https://parcs.canada.ca/pn-np/qc/mauricie/nature/conservation/protection-protecting/tortue-des-bois-wood-turtle>
5.  Radio-Canada. 2023. Les petites tortues d'un programme de repeuplement relâchées dans une rivière du Témiscouata. Consulté sur <https://ici.radio-canada.ca/nouvelle/1904654/tortues-des-bois-programme-repeuplement-temiscouata>

### Statistical analysis

6.  Cormack, R. M. 1964. Estimates of Survival from the Sighting of Marked Animals. Biometrika 51 (3-4): 429–38. <https://doi.org/10.1093/biomet/51.3-4.429>
7.  Jolly, G. M. 1965. Explicit Estimates from Capture recapture Data with Both Death and Immigration: Stochastic Model. Biometrika 52: 225–47.
8.  Seber, G. A. 1965. A Note on the Multiple Recapture Census. Biometrika 52: 249–49.
9.  Von Bertalanffy, L. 1960. Principles and theory of growth. Nowinski, W.W., Ed., Fundamental Aspects of Normal and Malignant Growth, Elsevier, Amsterdam, 137-259.

### Results

10. Wisconsin Department of Natural Resources. 2016. Wisconsin Wood Turtle (*Glyptemys insculpta*) Status Assessment and Conservation Strategy. Wisconsin Department of Natural Resources, Madison, Wisconsin, USA. <https://www.researchgate.net/publication/312056576_Wisconsin_Wood_Turtle_Glyptemys_insculpta_Status_Assessment_and_Conservation_Strategy_April_2016>
11. Pearl, R. 1928. The rate of living. Knop, New York
12. 

<iframe src="CHS.pdf" width="100%" height="80vh" style="border:1px solid #ccc;">

</iframe>
